### ISSUE TITLE
Maximum sequence length 

### ISSUE THREAD

**Issue by wise-east** [microsoft/DialoGPT#34]
On the README, it says that the default max_seq_length is 128. Was this the actual parameter used for training the models? 

If so, does that mean without further fine-tuning or training a model from scratch with a longer max_seq_length, the trained models will not be able to generate proper responses for input sequences that are longer than 128 or have the responses cut short at 128? I'm asking because it seems like the case if I provide a context that is too long, about 120 tokens, then it would only generate about 8 tokens and stop, making the output get cut short.

**Comment by GraphGrailAi** [comment]
I support question

**Comment by intersun** [comment]
You are right, this is the parameter we used for training because 
(1) we are dealing with 1-turn response, 128 typically is long enough
(2) and training can be done faster given limited computation resource we have at that time.

So for longer context we are not sure what will happen since the position encoding of that part never got touched... 

You could fine-tune the model with longer materials though just to learn the positional encoding, this technique is adopted in original BERT paper (train with len=128 first, then further train with len=512).
